version: "3"
services:
  front:
    container_name: react
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run dev"
  back:
    container_name: flask
    build: ./back
    ports:
      - "5001:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    # hot reload
    command: flask run --host=0.0.0.0 --reload
